In [2]:
import numpy as np

In [4]:
lista = [1,2,3,4,5,6,7,8]
lista

[1, 2, 3, 4, 5, 6, 7, 8]

In [7]:
arr = np.array(lista)

In [8]:
type(arr)

numpy.ndarray

In [9]:
matriz = [[1,2,3],[4,5,6],[7,8,9]]
matriz = np.array(matriz)
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
arr[1]
arr[5] + arr[2]

9

In [17]:
matriz[2]
matriz[0,2]

3

In [24]:
arr[0:3]
arr[:6]
arr[2:]
arr[::2]
arr[-1]
arr[-3]
arr[-3:]

array([6, 7, 8])

In [25]:
matriz[1:,0:2]

array([[4, 5],
       [7, 8]])