# Funcion Copy

In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
trozo_de_array = arr[0:6]
trozo_de_array

array([0, 1, 2, 3, 4, 5])

In [4]:
trozo_de_array[:] = 0

In [5]:
trozo_de_array

array([0, 0, 0, 0, 0, 0])

In [6]:
arr

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

In [7]:
arr_copy = arr.copy()

In [8]:
arr_copy[:] = 100
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [9]:
arr

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

In [10]:
id(arr)

140018349894672

In [11]:
id(arr_copy)

140018349895248