# Creando arrays

In [1]:
import numpy as np

In [3]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

## Uso de arange
Se puede hacer uso de np.arange para poder crear un array de forma automatica

In [4]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

Llenando un array con zeros

In [8]:
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

Llenado de un array con unos

In [9]:
np.ones((10,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

Creacion de una distribucion normalizada con espacios iguales en un rango

In [10]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

Creacion de una matriz identidad de n dimesiones

In [11]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

Creacion de una matriz con datos totalmente randon

In [14]:
np.random.rand(4,5)

array([[0.82038626, 0.52480131, 0.91356696, 0.58167738, 0.347975  ],
       [0.29251784, 0.64919173, 0.80408372, 0.24981737, 0.03023128],
       [0.70583676, 0.40678353, 0.74459117, 0.40370617, 0.37664689],
       [0.43400731, 0.7325476 , 0.30470136, 0.07187413, 0.20866879]])

In [15]:
np.random.randint(1,15)

6

In [16]:
np.random.randint(1,100,(10,10))

array([[81, 22, 81, 40, 83, 85,  3, 79, 64, 11],
       [ 9,  2, 26, 81, 22, 39, 39, 77, 55, 73],
       [40, 77, 56, 64, 27, 14, 22, 62, 21, 24],
       [66, 71,  4, 19, 41, 53, 37, 56, 96, 97],
       [85, 43, 85,  9, 42, 24, 55, 87,  6, 94],
       [ 8, 42, 32, 45, 40, 94, 40, 53, 79, 64],
       [51, 48, 83, 57, 31, 46, 65, 14, 23, 87],
       [ 5, 11,  1, 24,  4, 42, 67, 63, 78,  2],
       [54, 60, 54, 57, 10, 99, 56, 43, 25, 50],
       [33, 67, 14, 67, 80, 48, 94, 94, 47, 27]])