# Funciones principales de NumPy

In [3]:
import numpy as np

In [4]:
arr = np.random.randint(1,20,10)

In [5]:
matriz = arr.reshape(2,5)
print(matriz)

[[12 19 17  3 16]
 [ 1 16  6  9  9]]


In [6]:
arr.max()

19

In [7]:
matriz.max()

19

## Funcion max() por filas y columnas
El valor de 0 representa el valor por columnas y el valor 1 representa por filas

In [8]:
matriz.max(0)

array([12, 19, 17,  9, 16])

In [9]:
matriz.max(1)

array([19, 16])

## Funcion argmax()
Este muestra el indice en el cual se encuentra el maximo valor en un vector o matriz

In [10]:
arr.argmax()

1

In [11]:
matriz.argmax(0)

array([0, 0, 0, 1, 0])

In [12]:
matriz.argmax(1)

array([1, 1])

In [13]:
arr.min()

1

In [14]:
matriz.min(0)

array([ 1, 16,  6,  3,  9])

In [15]:
matriz.min(1)

array([3, 1])

In [16]:
arr.argmin()

5

In [17]:
matriz.argmin(0)

array([1, 1, 1, 0, 1])

In [18]:
matriz.argmin(1)

array([3, 0])

## Funcion ptp()
Esto nos muestra cual es la diferencia entre el pico mas alto y el pico mas bajo

In [19]:
arr.ptp()

18

In [20]:
matriz.ptp(0)

array([11,  3, 11,  6,  7])

In [21]:
matriz.ptp(1)

array([16, 15])

## Funcion percentile()
Da como resultado el percentil

In [22]:
np.percentile(arr,50)

10.5

In [25]:
arr.sort()
print(arr)

[ 1  3  6  9  9 12 16 16 17 19]


In [28]:
np.percentile(arr,100)

19.0

In [29]:
np.percentile(arr, 0)

1.0

In [30]:
np.median(arr)

10.5

In [31]:
np.median(matriz, 0)

array([ 6.5,  9.5, 11. , 13. , 14. ])

In [32]:
np.std(arr)

5.89576118919347

In [33]:
np.var(arr)

34.760000000000005

In [34]:
np.std(arr)**2

34.76

In [35]:
np.mean(arr)

10.8

In [36]:
a = np.array([[1,2], [3,4]])

In [37]:
a

array([[1, 2],
       [3, 4]])

In [38]:
b = np.array([5,6])

In [39]:
b

array([5, 6])

In [41]:
b = np.expand_dims(b, axis=0)

In [42]:
np.concatenate((a,b),axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])