# Operaciones


In [1]:
import numpy as np

In [2]:
lista = [1,2]
lista

[1, 2]

In [4]:
lista

[1, 2]

In [5]:
arr = np.arange(0,11)

In [6]:
arr2 = arr.copy()

In [7]:
print(arr)
print(arr2)

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  1  2  3  4  5  6  7  8  9 10]


## Operaciones aritmeticas en elementos

In [8]:
arr * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [9]:
arr + 2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [11]:
11 / arr

/tmp/ipykernel_6513/2438797433.py:1: RuntimeWarning: divide by zero encountered in divide
  11 / arr


array([        inf, 11.        ,  5.5       ,  3.66666667,  2.75      ,
        2.2       ,  1.83333333,  1.57142857,  1.375     ,  1.22222222,
        1.1       ])

In [12]:
arr + arr2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [13]:
arr * arr2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

## Operaciones con matrices

In [15]:
arr = np.arange(0,10)
matriz = arr.reshape(2,5)
matriz

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [16]:
matriz3 = arr.reshape(5,2)

In [17]:
matriz3

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [18]:
matriz2 = matriz.copy()

In [19]:
matriz + matriz2

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [20]:
matriz * matriz2

array([[ 0,  1,  4,  9, 16],
       [25, 36, 49, 64, 81]])

In [21]:
np.matmul(matriz, matriz3)

array([[ 60,  70],
       [160, 195]])

In [22]:
matriz @ matriz3

array([[ 60,  70],
       [160, 195]])

In [23]:
np.dot(matriz, matriz3)

array([[ 60,  70],
       [160, 195]])

In [24]:
matriz.dot(matriz3)

array([[ 60,  70],
       [160, 195]])