# Shape y Reshape
## Shape
Esto hace alusion a la forma que tiene el arreglo

In [1]:
import numpy as np

In [3]:
arr = np.random.randint(1,10,(3,2))

In [4]:
arr.shape

(3, 2)

In [5]:
arr.reshape(1,6)

array([[2, 7, 2, 6, 2, 2]])

In [6]:
arr.reshape(2,3)

array([[2, 7, 2],
       [6, 2, 2]])

In [7]:
np.reshape(arr, (1,6))

array([[2, 7, 2, 6, 2, 2]])

## Redimensionado
Esto se puede hacer de 3 formas diferentes los cuales son: Como el lenguaje C 'C', como el lenguaje Fortran 'F' o de la forma como esta optimizado en nuestra PC 'A'

In [9]:
arr

array([[2, 7],
       [2, 6],
       [2, 2]])

### Como el lenguaje C

In [10]:
np.reshape(arr, (2,3), 'C')

array([[2, 7, 2],
       [6, 2, 2]])

### Como el lenguaje Fortran

In [11]:
np.reshape(arr, (2,3), 'F')

array([[2, 2, 6],
       [2, 7, 2]])

### Como esta optimizado en nuestra PC

In [12]:
np.reshape(arr, (2,3), 'A')

array([[2, 7, 2],
       [6, 2, 2]])